name: bencher_bbob_linearslope_6_400
n_tot: 500
n_init: 30
fn:
  _target_: src.benchmarks.embedded.EmbeddedTestFunction
  d_ambient: 400
  negate: true
  inner_fn:
    _target_: src.benchmarks.bencher_wrapper.BencherTestFunction
    benchmark_name: bbob-linearslope
    dim: 6
    address: "127.0.0.1"
    port: 50051
    negate: false